version: '3.4'
services:
  chatbot:
    image: chatbot
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
  node_modules:
