version: '3.4'
services:
  chatbot:
    image: registry.digitalocean.com/pump-factory/chatbot
    working_dir: /app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
