version: '3'
services:
  web:
    build: ./
    working_dir: /app
    command: npm start
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: accountability-bot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: accountability-bot
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
volumes:
  postgres_data:
  node_modules:
